-- ============================================================
-- Sample data seeded from the original Excel trackers
-- Run AFTER schema.sql, once you have signed up at least one user
-- ============================================================

insert into leads (lead_name, contact_name, topic_sku, salesperson, date_received, status, next_action, follow_up_date) values
('Green Gas Services', 'Jessica Smith', 'D365 BC', 'Ivan', '2026-04-13', 'Contacted', 'Sent email', '2026-04-22'),
('Inboden Environmental Services, Inc', 'Audra Stuart', 'D365 BC (from QB)', 'Santiago', '2026-04-16', 'Contacted', 'Sent email', '2026-04-23'),
('Ragle Inc', 'George Oroni', 'D365 HR', 'Daniel Melo', '2026-04-15', 'Contacted', NULL, NULL),
('Hold Point Pet', 'Oliver Dunlap', 'D365 BC', 'Kevin Agudelo', '2026-04-21', 'Contacted', NULL, NULL),
('B2 Medical', 'Bradley Nichols', 'QB to BC', 'Santiago', '2026-04-20', 'Contacted', 'Sent email', NULL),
('Medical Legal Expertise', 'Steven Walker', 'QB to BC', 'Santiago', '2026-04-20', 'Contacted', NULL, NULL),
('Colis Express LLC', 'Matui Adossi', NULL, 'Kevin Agudelo', '2026-04-17', 'Contacted', 'License Email to be shared', NULL),
('Army Ten Miler', NULL, 'D365 BC', 'Santiago', '2026-04-27', 'Contacted', 'Check with Santiago', NULL),
('Division 10 Sales', NULL, 'D365 Sales', 'Kevin Agudelo', '2026-04-27', 'Contacted', 'Starter Package?', NULL),
('Easy Mile', NULL, 'D365 BC', 'Santiago', NULL, 'Contacted', 'Demo Done', NULL),
('Monarch Supplies', 'Peter ILL', 'D365 BC', 'Santiago', '2026-04-15', 'Contacted', 'Disqualified - since this may need GCC High', NULL),
('Personalysis Corporation', 'Kecia McBride', 'D365 Sales', 'Juan Diaz', '2026-04-15', 'Contacted', NULL, '2026-04-16'),
('Vanns Spices', 'Nick Ciotti', 'D365 BC - Supply Chain', 'Kevin Agudelo', '2026-04-15', 'Contacted', NULL, NULL),
('Helm Holding International', 'Manny Carreno', 'D365 BC', 'Santiago', '2026-04-14', 'Contacted', 'Demo scheduled: 04/21 1pm', '2026-04-21'),
('GOA Logistics', 'Ryan', 'D365 Sales', 'Kevin Agudelo', '2026-04-14', 'Won', 'WON', '2026-04-16'),
('HME Workforce', 'Toli Kotsaspyrou', 'Power Automate', 'Kevin Agudelo', '2026-04-14', 'Contacted', NULL, NULL),
('AEG', 'Joe Tallant', 'D365 Sales', 'Kevin Agudelo', '2026-04-14', 'Contacted', 'Demo Scheuled: 04/23 2pm', '2026-04-23'),
('VIP Wireless Hold', 'Paul Cerullo', 'D365 BC', 'Ivan', '2026-04-13', 'Contacted', 'Moving in different Direction', NULL),
('Robert McNeel', 'Jennifer Byrne', 'D365 BC', 'Santiago', '2026-04-10', 'Won', 'WON', '2026-04-14'),
('SMC Components', 'Louis', 'D365 BC', 'Santiago', '2026-04-15', 'Won', 'WON', NULL),
('Ball Chain Mftg', 'Catherine Taubner', 'D365 CI-J', 'Ivan', '2026-04-09', 'Contacted', NULL, NULL),
('DeJoy & Co', 'Chelsea Newton', 'NAV to D365 BC', 'Santiago', '2026-04-02', 'Contacted', 'Demo Done: 04/14', '2026-04-14'),
('eHeart Interior', NULL, 'D365 BC', NULL, '2026-04-02', 'Contacted', 'Awaiting Nex Steps - demo to larger team', '2026-04-02'),
('Omnidya', 'Steven Luong', 'D365 FO', 'Santiago', '2026-04-13', 'Contacted', 'Demo to be scheduled', '2026-04-27'),
('Built at Dawn Supply', NULL, 'BC + Shopify', 'Santiago', '2026-04-08', 'Contacted', 'Contract shared', NULL),
('Alair Homes', NULL, 'Vendor Mgmt', NULL, '2026-04-08', 'Contacted', NULL, NULL),
('Bastion Standard', NULL, 'D365 BC', NULL, '2026-04-06', 'Contacted', NULL, NULL),
('Studio MA', NULL, 'D365 Sales', 'Ivan', '2026-04-03', 'Contacted', 'Decided to go for Industry specific CRM', NULL),
('K Systems Soln', NULL, 'Vendor Mgmt', NULL, '2026-04-01', 'Contacted', 'Demo to be scheduled', NULL),
('Pugh Capital', NULL, 'D365 BC', 'Santiago', '2026-03-30', 'Contacted', 'Demo: 04/17', '2026-04-17'),
('Foundation Lenders', NULL, 'D365 Sales', 'Santiago', '2026-03-26', 'Contacted', NULL, '2026-04-01');

insert into leads (lead_name, contact_name, topic_sku, salesperson, date_received, status, next_action, source, segment) values
('Quixlabs', 'Zachary Starr', 'D365 BC', 'Santiago', '2026-06-15', 'Contacted', '07/01 shared estimate', 'Recap Email', NULL),
('Crazy Creek', 'Karson Bagby', 'D365 BC', 'Santiago', '2026-06-12', 'Contacted', '07/01 Demo', 'Recap Email', 'S'),
('Cobblestone Bakery Corp', 'Frank LaFerlita', 'D365 BC', 'Kevin Agudelo', '2026-06-11', 'Contacted', '06/29 reminder', 'Recap Email', 'G'),
('Four Feathers', 'Jefferson Hamilton', 'D365 BC', 'Santiago', '2026-06-11', 'Contacted', '06/29  Followup', 'Recap Email', 'G'),
('Shazmode USA', 'Najam Mufti', 'D365 BC', 'Santiago', '2026-06-11', 'Contacted', '06/30 Share estimate', 'Recap Email', 'S'),
('Green Light Promotions', 'Jessica Burbank', 'D365 Sales', NULL, '2026-06-01', 'Contacted', '06/29 Follow Up', 'Partner Center', 'S'),
('Taos Footwear', 'Oscar Campos', 'D365 Sales', NULL, '2026-06-01', 'Contacted', '08/01: a) FOLLOW UP 7/02 b) Estimate to be shared', 'Partner Center', 'G'),
('TCS Heating and Air', 'Bill Burke', 'D365 Marketing (CI-J)', NULL, '2026-06-01', 'Contacted', '2-Jun', NULL, 'S'),
('Geo Prime Energy', 'Ademola Fagade', NULL, NULL, NULL, 'Contacted', '06/29 Follow up', NULL, 'G'),
('Arivasense', 'Hamsatharini Shan-Nath', 'D365 BC Sales', 'Santiago', '2026-05-21', 'Contacted', '06/25 Send e sign agreement', NULL, NULL),
('Alsico North America', 'Jacob Boje', 'D365 BC', NULL, '2026-05-19', 'Contacted', '06/29 Follow Up', 'Partner Center', NULL),
('MeaeCare', 'Aliya Ghoreichi', 'D365 BC', NULL, '2026-05-19', 'Contacted', '06/23 call Followup', 'Partner Center', 'S'),
('Cambridge Isotope Laboratories', 'Amy Elkington', 'Azure', 'ALLETEC Inbound', '2026-05-18', 'Contacted', '06/16 follow up', 'Partner Center', NULL),
('Flight Pro International', 'Joseph Mayoraga', 'D365 Contact Center', NULL, '2026-05-15', 'Contacted', '06/15 send quote', 'Partner Center', NULL),
('lequities', 'Chrysalis Ramos', 'D365 BC', NULL, '2026-05-15', 'Contacted', '06/29 email', NULL, 'G'),
('LINDBLAD EXPEDITIONS', NULL, 'D365 ERP', NULL, '2026-05-15', 'Contacted', '06/24 demo', NULL, NULL),
('Double K industries', 'Grant Parrinello', NULL, NULL, '2026-05-02', 'Contacted', '06/30 Follow up', NULL, 'G'),
('Liberation bio industries', 'Don Farias', 'D365 BC', NULL, NULL, 'Contacted', '06/30 Follow up', NULL, 'G'),
('Encina', 'Dale Schwieger', NULL, NULL, NULL, 'Contacted', '06/25 Follow up', NULL, 'S'),
('Vista Clara', 'Amanda Young', 'D365 BC', 'Santiago', '2026-04-27', 'Contacted', '07/31 Follow Up', 'Recap Email', 'G'),
('Nviro', 'Ryan Swenson', 'D365 BC Sales', NULL, NULL, 'Contacted', '06/30 follow up', NULL, NULL),
('scale resource group', 'Brian Moore', 'D365 BC', 'Santiago', NULL, 'Contacted', 'Follow up', NULL, NULL),
('Top Tier Utility', 'Donovan Rhoades', 'D365 BC + Sales', NULL, '2026-06-10', 'Contacted', 'Follow up', NULL, NULL),
('Rayco Marina Construction, Inc', 'Caleb Dupuis', 'D365 BC', 'Ricardo Falconi.', '2026-06-09', 'Contacted', '06/23 Follow up', NULL, NULL),
('Yuno Group USA, LLC', 'Eric Fischer', 'BC', NULL, '2026-06-01', 'Contacted', '06/23 Follow up', 'Partner Center', 'S'),
('Naebom Business', 'Yomaira Munoz-Salazar', 'D365 Sales + D365 BC', NULL, '2026-05-20', 'Contacted', 'Close; unless response received', 'Recap Email', NULL),
('PUcore USA Inc.', 'Ken Zamora', 'D365 Sales', 'Nicolas', '2026-05-20', 'Contacted', '06/03 Demo', 'Recap Email', NULL),
('Smart Gladiator LLC', 'Anusha Varikuti', 'D365 Sales + D365 BC', NULL, '2026-05-20', 'Contacted', '19600', 'Partner Center', NULL),
('Purple Light Tech Corporation', 'Bell Ke', 'CRM', 'Santiago', '2026-06-02', 'Contacted', NULL, NULL, 'S'),
('GLC distribuition', 'Jennifer Fergel', NULL, NULL, '2026-05-02', 'Contacted', '05/28:  Call CLOSED', NULL, NULL),
('Bastion Standard Company', 'Dioly Alexandre', 'D365 BC', NULL, '2026-04-01', 'Contacted', NULL, NULL, 'G'),
('Code and Trust', NULL, NULL, NULL, NULL, 'Contacted', 'Closed', NULL, NULL);

insert into licenses (customer_name, agreement_client_signed, agreement_countersigned, invoice_shared, payment_done, payment_confirmed, license_loaded, sku, license_qty, subscription_type, amount, status, roles_notes) values
('MC calla', false, false, false, false, false, false, 'BC Essentials', 2, 'A', 0, 'Pending', NULL),
('Resia', false, false, false, false, false, false, 'BC Team Memeber', 25, 'A', 0, 'Pending', NULL),
('Guild & Facet', true, true, false, true, true, true, 'BC Essentials', 3, 'M', 3456, 'Active', 'signed agreement, accept reseller link'),
('Ragle Inc', true, true, true, true, true, true, 'D365 HR  Team Member (1)', 5, 'M', 6300, 'Active', 'counter sign by sandeep, create account in bc'),
('Colis Express', true, true, true, false, false, false, 'BC Essentials', 1, 'M', 960, 'Pending', 'assigning licesnes to customer'),
('Scale Resource Group', true, true, true, true, true, false, 'BC Essentials', 2, 'A', 1920, 'Pending', NULL),
('Top Tier Utility', true, true, true, true, true, false, 'MS Office D365 BC', 1, 'A', 4944, 'Pending', NULL),
('Yuno Group', true, true, true, false, false, false, 'D365 BC Essentials', 3, 'A', 2880, 'Pending', NULL),
('Rayco Marine', true, true, true, true, true, false, 'D365 BC Premium', 2, 'M', 1920, 'Pending', NULL);
